# create_package(here::here("invSCI"))
# git init
library(devtools)
use_mit_license()
usethis::use_package("dplyr")
usethis::use_package("mgcv")
usethis::use_package("MASS")
usethis::use_package("nlme")
usethis::use_package("fields")
usethis::use_package("maps")
usethis::use_package("metR")
usethis::use_package("ggpubr")
usethis::use_package("ggplot2")
usethis::use_package("patchwork")
usethis::use_package("grDevices")
usethis::use_package("forcats")
usethis::use_package("stats")
usethis::use_package("tibble")
usethis::use_package("tidyr")
usethis::use_package("refund")

usethis::use_import("patchwork")
usethis::use_import("reshape")
usethis::use_import("forcats")

usethis::use_import_from("mgcv", "bam")
usethis::use_import_from("mgcv", "gam")
usethis::use_import_from("tibble", "as_tibble")
usethis::use_import_from("MASS", "mvrnorm")
usethis::use_import_from("magrittr", "%>%")
usethis::use_import_from("fields", c("image.plot", "image.smooth", "interp.surface"))
usethis::use_import_from("maps", "map")
usethis::use_import_from("graphics", "lines")
usethis::use_import_from("dplyr", c("mutate", "desc", "filter", "select", "arrange", "left_join"))
usethis::use_import_from("reshape", "melt")
usethis::use_import_from("forcats","fct_reorder")
usethis::use_import_from("tidyr","pivot_wider")
usethis::use_import_from("refund","fpca.face")
usethis::use_import_from("matrixStats","rowVars")

dir.create("inst/extdata", recursive = TRUE, showWarnings = FALSE)

usethis::use_data_raw("ccds_preprocess")
usethis::use_data_raw("ccds_load")
usethis::use_data_raw("ccds_fpca")
usethis::use_data_raw("climate_data")
usethis::use_data_raw("ccds_cma")

usethis::use_r("data_ccds")
usethis::use_r("data_climate")
usethis::use_r("global")
usethis::use_r("functional_outcome_scb")

devtools::document()
devtools::install()
devtools::load_all()
devtools::check()

touch README.Rmd
devtools::build_readme()

usethis::use_testthat(3)
usethis::use_test("cma")
usethis::use_test("functional_outcome_scb")
usethis::use_test("MultiplierBootstrap")
usethis::use_test("plot_cs")
usethis::use_test("regression_outcome_scb")
usethis::use_test("SCB_dense")
usethis::use_test("scb_to_cs")
